### ISSUE TITLE
Compare your version and official version in README

### ISSUE THREAD

**Issue by YijunYuan** [ayaka-notes/overleaf#3]
虽然作者在blog中已经提到了此版本和overleaf官方的free版比起来多了什么功能，但作为一个完整的github repo，我想也许可以在readme中做一个表格将此版本、official free与official pro进行功能上的对比，并给出TODO list或者roadmap。这样会极大地方便用户了解此版本的优点以及未来会变成什么样子

**Comment by Musicminion** [comment]
好的，感谢喵！
