### ISSUE TITLE
docker logs when starting

### ISSUE THREAD

**Issue by cosine123** [ayaka-notes/overleaf#4]
root@123:/gitlab/overleaf# docker logs -f d7ef85e005f8
*** Running /etc/my_init.d/000_check_for_old_bind_mounts_5.sh...
*** Running /etc/my_init.d/000_check_for_old_env_vars_5.sh...
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/100_generate_secrets.sh...
generating random secrets
*** Running /etc/my_init.d/100_make_overleaf_data_dirs.sh...
*** Running /etc/my_init.d/100_restore_site_status.sh...
*** Running /etc/my_init.d/100_set_docker_host_ipaddress.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
[2024-03-21T06:35:55.116900] file ../../../glib/gthread-posix.c: line 1339 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create'
/etc/my_init.d/10_syslog-ng.init: line 32:    80 Trace/breakpoint trap   (core dumped) /usr/sbin/syslog-ng --pidfile "$PIDFILE" -F $SYSLOGNG_OPTS
*** /etc/my_init.d/10_syslog-ng.init failed with status 1

*** Killing all processes...
*** Running /etc/my_init.d/000_check_for_old_bind_mounts_5.sh...
*** Running /etc/my_init.d/000_check_for_old_env_vars_5.sh...
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/100_generate_secrets.sh...
*** Running /etc/my_init.d/100_make_overleaf_data_dirs.sh...
*** Running /etc/my_init.d/100_restore_site_status.sh...
*** Running /etc/my_init.d/100_set_docker_host_ipaddress.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
[2024-03-21T06:38:36.996762] file ../../../glib/gthread-posix.c: line 1339 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create'
/etc/my_init.d/10_syslog-ng.init: line 32:    52 Trace/breakpoint trap   (core dumped) /usr/sbin/syslog-ng --pidfile "$PIDFILE" -F $SYSLOGNG_OPTS
*** /etc/my_init.d/10_syslog-ng.init failed with status 1

*** Killing all processes...

**Comment by cosine123** [comment]
我的设备上运行，需要docker-compose.yml里每个容器都设定privileged: true

**Comment by Musicminion** [comment]
> 我的设备上运行，需要docker-compose.yml里每个容器都设定privileged: true

可能是要把当前用户加到docker组里面？然后就不需要sudo？（我猜测是这样

**Comment by Musicminion** [comment]
> root@123:/gitlab/overleaf# docker logs -f d7ef85e005f8 *** Running /etc/my_init.d/000_check_for_old_bind_mounts_5.sh... *** Running /etc/my_init.d/000_check_for_old_env_vars_5.sh... *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh... *** Running /etc/my_init.d/100_generate_secrets.sh... generating random secrets *** Running /etc/my_init.d/100_make_overleaf_data_dirs.sh... *** Running /etc/my_init.d/100_restore_site_status.sh... *** Running /etc/my_init.d/100_set_docker_host_ipaddress.sh... *** Running /etc/my_init.d/10_syslog-ng.init... [2024-03-21T06:35:55.116900] file ../../../glib/gthread-posix.c: line 1339 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create' /etc/my_init.d/10_syslog-ng.init: line 32: 80 Trace/breakpoint trap (core dumped) /usr/sbin/syslog-ng --pidfile "$PIDFILE" -F $SYSLOGNG_OPTS *** /etc/my_init.d/10_syslog-ng.init failed with status 1
> 
> *** Killing all processes... *** Running /etc/my_init.d/000_check_for_old_bind_mounts_5.sh... *** Running /etc/my_init.d/000_check_for_old_env_vars_5.sh... *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh... *** Running /etc/my_init.d/100_generate_secrets.sh... *** Running /etc/my_init.d/100_make_overleaf_data_dirs.sh... *** Running /etc/my_init.d/100_restore_site_status.sh... *** Running /etc/my_init.d/100_set_docker_host_ipaddress.sh... *** Running /etc/my_init.d/10_syslog-ng.init... [2024-03-21T06:38:36.996762] file ../../../glib/gthread-posix.c: line 1339 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create' /etc/my_init.d/10_syslog-ng.init: line 32: 52 Trace/breakpoint trap (core dumped) /usr/sbin/syslog-ng --pidfile "$PIDFILE" -F $SYSLOGNG_OPTS *** /etc/my_init.d/10_syslog-ng.init failed with status 1
> 
> *** Killing all processes...

服务器和docker版本？是ubuntu+最新docker的吗

**Comment by cosine123** [comment]
Ubuntu20.04 docker20.10.09



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 22, 2024 22:10 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ayaka-notes/overleaf] docker logs when starting (Issue #4)




  
***@***.***:/gitlab/overleaf# docker logs -f d7ef85e005f8 *** Running /etc/my_init.d/000_check_for_old_bind_mounts_5.sh... *** Running /etc/my_init.d/000_check_for_old_env_vars_5.sh... *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh... *** Running /etc/my_init.d/100_generate_secrets.sh... generating random secrets *** Running /etc/my_init.d/100_make_overleaf_data_dirs.sh... *** Running /etc/my_init.d/100_restore_site_status.sh... *** Running /etc/my_init.d/100_set_docker_host_ipaddress.sh... *** Running /etc/my_init.d/10_syslog-ng.init... [2024-03-21T06:35:55.116900] file ../../../glib/gthread-posix.c: line 1339 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create' /etc/my_init.d/10_syslog-ng.init: line 32: 80 Trace/breakpoint trap (core dumped) /usr/sbin/syslog-ng --pidfile "$PIDFILE" -F $SYSLOGNG_OPTS *** /etc/my_init.d/10_syslog-ng.init failed with status 1
 
*** Killing all processes... *** Running /etc/my_init.d/000_check_for_old_bind_mounts_5.sh... *** Running /etc/my_init.d/000_check_for_old_env_vars_5.sh... *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh... *** Running /etc/my_init.d/100_generate_secrets.sh... *** Running /etc/my_init.d/100_make_overleaf_data_dirs.sh... *** Running /etc/my_init.d/100_restore_site_status.sh... *** Running /etc/my_init.d/100_set_docker_host_ipaddress.sh... *** Running /etc/my_init.d/10_syslog-ng.init... [2024-03-21T06:38:36.996762] file ../../../glib/gthread-posix.c: line 1339 (g_system_thread_new): error 'Operation not permitted' during 'pthread_create' /etc/my_init.d/10_syslog-ng.init: line 32: 52 Trace/breakpoint trap (core dumped) /usr/sbin/syslog-ng --pidfile "$PIDFILE" -F $SYSLOGNG_OPTS *** /etc/my_init.d/10_syslog-ng.init failed with status 1
 
*** Killing all processes...
  
服务器和docker版本？是ubuntu+最新docker的吗

**Comment by Musicminion** [comment]
暂时关闭了吧我还是，如果还有问题再提？
