### ISSUE TITLE
运行./dev.sh后编译论文报错

### ISSUE THREAD

**Issue by nmvbxcz** [ayaka-notes/overleaf#5]
clone了整个项目，然后使用了./dev.sh
![image](https://github.com/ayaka-notes/overleaf/assets/15317138/9ec52de1-707d-4601-8f1b-a3df9aa7a6b4)
docker启动了多个容器后可以打开网页，但是无法编译（中英文都不行），同时不知道后续对中文论文的支持如何
![image](https://github.com/ayaka-notes/overleaf/assets/15317138/f4c15051-972b-4f22-b8d7-386ce5b3fa5f)
Server Error
Sorry, something went wrong and your project could not be compiled. Please try again in a few moments.

**Comment by nmvbxcz** [comment]
好像是因为 ghcr.io/ayaka-notes/overleaf/texlive:2023.1  这些编译都无法访问了

**Comment by nmvbxcz** [comment]
到底是先弄这个？
 # 注意：COMPILE_TIMEOUT必须在所有数据初始化之前生效
      # 因为编译时间是和用户强相关的，每个用户有自己的编译时间限制
      # 如果你服务器运行很久了，需要手动写脚本，更新mongo数据库中的用户编译时间限制
      COMPILE_TIMEOUT: "600"
      DOCKER_RUNNER: "true"
      SANDBOXED_COMPILES: "true"
      SANDBOXED_COMPILES_SIBLING_CONTAINERS: "true"
      # 记得改/workspaces/overleaf为你的克隆下来的仓库的路径
      SANDBOXED_COMPILES_HOST_DIR: "/workspaces/overleaf/data/sharelatex_data/data/compiles"
      SYNCTEX_BIN_HOST_PATH: "/workspaces/overleaf/data/sharelatex_data/bin" 
      TEX_LIVE_DOCKER_IMAGE: "ghcr.io/ayaka-notes/overleaf/texlive:2023"
      ALL_TEX_LIVE_DOCKER_IMAGES: "ghcr.io/ayaka-notes/overleaf/texlive:2023,ghcr.io/ayaka-notes/overleaf/texlive:2022,ghcr.io/ayaka-notes/overleaf/texlive:2021"
还是执行./dev.sh，这样会覆盖之前的修改，搞蒙了

**Comment by Musicminion** [comment]
你好哦，dev那个脚本已经被我弃用了，请不要使用！

**Comment by Musicminion** [comment]
> 好像是因为 ghcr.io/ayaka-notes/overleaf/texlive:2023.1 这些编译都无法访问了
> {"name":"clsi","hostname":"e681164fffea","pid":29,"level":50,"err":{"message":"(HTTP code 404) no such container - No such image: texlive-full:latest ","name":"Error","stack":"Error: (HTTP code 404) no such container - No such image: texlive-full:latest \n at /overleaf/node_modules/docker-modem/lib/modem.js:324:17\n at getCause (/overleaf/node_modules/docker-modem/lib/modem.js:354:7)\n at Modem.buildPayload (/overleaf/node_modules/docker-modem/lib/modem.js:323:5)\n at IncomingMessage. (/overleaf/node_modules/docker-modem/lib/modem.js:295:14)\n at IncomingMessage.emit (node:events:529:35)\n at endReadableNT (node:internal/streams/readable:1400:12)\n at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","info":{}},"projectId":"66016fcb4e3916062e6c7c38","msg":"error running compile","time":"2024-03-26T03:09:03.209Z","v":0}

因为你需要把这个镜像先拉下来，才能编译哦！
